### ISSUE TITLE
Rozdzielenie sealious-www-server i sealious-channel-rest

### ISSUE THREAD

**Issue by kuba-orlik** [Sealious/sealious-base-chips#31]
Czas na ciąg dalszy porządkowania struktury Sealiousowej.
Należy z sealious-www-server wyodrębnić sealious-channel-rest. Ktoś może chcieć mieć serwer plików www, w którym nie ma RESTowego API. 

`sealious-channel-rest` powinien mieć `sealious-www-server` w `dependencies`

**Comment by modliszka** [comment]
There is a problem with testing changes in `sealiuos-www-server` plugin. 
Path of files looks like this:

![path](https://cloud.githubusercontent.com/assets/9070671/9760816/afe24c22-56f8-11e5-9779-20cf18c3f48e.png)

The problem is to communicate `index.js` (from app) with objects created in `node_modules-> sealious-www-server -> sealious-www-server.js` (for example `www_server`).
When we use `var Sealious = require(../../sealious);` in `sealious-www-server`, the objects are creating in plugin (console logs are ok), but there is an error in our app, that there is no chip with name "www_server":

```
E:\Projekt Sealious\sealious-example>node .
13:36:05.084 - info: Detected plugin sealious-www-server
13:36:05.193 - info: Detected plugin sealious-datastore-tingo
E:\Projekt Sealious\sealious-example\node_modules\sealious\lib\chip-types\chip-manager.js:86
    throw new Sealious.Errors.Error("ChipManager was asked to return a chip of
          ^
Error: ChipManager was asked to return a chip of type `channel` and name `www_server`, but it was not found
    at new SealiousErrors.Error (E:\Projekt Sealious\sealious-example\node_modules\sealious\lib\response\error.js:6:12)
    at get_chip (E:\Projekt Sealious\sealious-example\node_modules\sealious\lib\chip-types\chip-manager.js:86:10)
    at Object.<anonymous> (E:\Projekt Sealious\sealious-example\index.js:12:39)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

The app used for testing is here: https://github.com/groovy354/sealious-example/

**Comment by modliszka** [comment]
Furthermore we shouldn't use relative paths to `sealious`, because when we will create app with REST plugin, the `sealious-www-server` will have longer path in compared to `sealiuos` in dependencies in rest app. I use it just 'for now' to be able to test our `example-app`.

**Comment by modliszka** [comment]
The error was fixed - there was problem with linked dependecies.   

The issue is done on branch: https://github.com/Sealious/sealious-www-server/tree/Issue%2331_split_into_two_repos, pull request: #36.
